### ISSUE TITLE
Config: esbuildConfig

### ISSUE THREAD

**Issue by v1rtl** [hyperlightjs/hyperlight#26]
Related: #5

There must be a way to extend bundler functionality similar to how Nextjs allows to tweak Webpack.

This could be done like this:

```ts
{
  esbuildConfig: (config) => ESBuild.Config
}
```

### details:

- `config` object with current config
- the function return value will be concatenated with original config

**Comment by BRA1L0R** [comment]
Can't get the esbuild before actually building it, this will be the final format:
```js
{
  esbuildConfig: (config) => BuildConfig
}
```

Build hooks will do the rest

**Comment by v1rtl** [comment]
closed with https://github.com/hyperlightjs/hyperlight/commit/d2262967ffa02053849a618af72475ea3d5ba23b
